version: '3'
services:
  mysql:
    image: mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_USER: administrator
      MYSQL_PASSWORD: carlospunk
      MYSQL_DATABASE: currencybird
      MYSQL_ROOT_PASSWORD: Carlospunk1#
    ports:
      - 3306:3306
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./backend/
    depends_on:
      - mysql
    volumes:
      - ./backend:/app
    ports:
      - 8000:8000
    environment:
      - DATABASE_HOST=mysql
      - DATABASE_PORT=3306
      - DATABASE_USER=administrator
      - DATABASE_PASS=carlospunk
      - DATABASE_NAME=currencybird
